#!/bin/sh

# Gradle start up script for POSIX generated by Gradle.

app_path=$0

while
    app_base=${app_path##*/}
    app_path=${app_path%"$app_base"}
    [ -h "$app_path$app_base" ]
do
    ls=$(ls -ld "$app_path$app_base")
    link=${ls#*' -> '}
    case $link in
      /*) app_path=$link;;
      *) app_path=$app_path$link;;
    esac
done

APP_HOME=$(cd "${app_path:-./}" && pwd -P) || exit

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ -n "$JAVA_HOME" ]; then
    JAVACMD="$JAVA_HOME/bin/java"
else
    JAVACMD=java
fi

if ! command -v "$JAVACMD" >/dev/null 2>&1; then
    echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH." >&2
    exit 1
fi

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

set -- \
    "-Dorg.gradle.appname=$app_base" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"

exec "$JAVACMD" $DEFAULT_JVM_OPTS "$@"
